### ISSUE TITLE
vcf2abook error

### ISSUE THREAD

**Issue by coachshea** [jspricke/python-abook#1]
I have just downloaded your project. First, let me say thank you. This could be the answer to something that I have been looking for for a long time. I have just starting using it and the abook2vcf conversion appears to be find, but every time I run vcf2abook I receive the following error

Traceback (most recent call last):
  File "/usr/local/bin/vcf2abook", line 9, in <module>
    load_entry_point('abook==0.2.1', 'console_scripts', 'vcf2abook')()
  File "/usr/local/lib/python3.4/dist-packages/abook-0.2.1-py3.4.egg/abook.py", line 311, in vcf2abook
  File "/usr/local/lib/python3.4/dist-packages/abook-0.2.1-py3.4.egg/abook.py", line 280, in abook_file
  File "/usr/local/lib/python3.4/dist-packages/abook-0.2.1-py3.4.egg/abook.py", line 256, in _write
  File "/usr/local/lib/python3.4/dist-packages/abook-0.2.1-py3.4.egg/abook.py", line 256, in <listcomp>
TypeError: expected bytes, bytearray or buffer compatible object

Any help is greatly appreciated.

**Comment by jspricke** [comment]
I guess that's a problem with python3, I've only used it with python2 but can have a look later today to port it to 3.

**Comment by coachshea** [comment]
Jochen,

Thank you for the very fast response, and I appreciate you being willing to to 
that. In the meantime, I recompiled with python2 (I have both on my machine, 
but python3 is the default) and now it almost works, but when I use stdout as 
the output (either explicitly or implicitly) I end up getting nothing on 
stdout, but then I check ls and I have a file created entitled <stdout>.

**Comment by jspricke** [comment]
How did you call it?

**Comment by coachshea** [comment]
I tried the following:

  vcf2abook filename
  vcf2abook filename -
  cat filename | vcf2abook
  cat filename | vcf2abook -
  cat filename | vcf2abook - -

They all seemed to produce the same results. It does seem to work when I 
supply a proper filename, which is how I will most often use it. I was just 
trying to run some quick tests and ran into this.

**Comment by coachshea** [comment]
I have been playing around with this some more, and although I have generally gotten the same results, I stumbled upon a rather odd situation. while trying to convert my adressbook back and forth (i.e. abook2vcf ~/.abook/addressbook | vcf2abook), I get getting the following error:

Traceback (most recent call last):
  File "/usr/local/bin/vcf2abook", line 9, in <module>
    load_entry_point('abook==0.2.1', 'console_scripts', 'vcf2abook')()
  File "build/bdist.linux-x86_64/egg/abook.py", line 311, in vcf2abook
  File "build/bdist.linux-x86_64/egg/abook.py", line 280, in abook_file
  File "build/bdist.linux-x86_64/egg/abook.py", line 254, in _write
  File "build/bdist.linux-x86_64/egg/configobj.py", line 2070, in write
  File "build/bdist.linux-x86_64/egg/configobj.py", line 2076, in write
  File "build/bdist.linux-x86_64/egg/configobj.py", line 1993, in _write_line
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

I did try varying levels of '-' and nothing seemed to help.

I hope I'm being more helpful than being a pane. I really love what you are trying to do here.

**Comment by jspricke** [comment]
I've just pushed a new version which should fix the `<stdout>` and encoding error. I also switched from the vobject lib to the fork card_me, but it still produces python3 errors.

Would be great if you can test it.

**Comment by coachshea** [comment]
I have pulled in your updates and recompiled. It works well for the most part 
with some exceptions. As per the new default, it saves to the 
.abook/addressbook when nothing is specified. However, if I specify outfile as 
- it get saved as a file named -. This is only a minor issue for me, because I
  have only been using that for testing purposes, but I thought you should know.

The other issue is more serious. I can run my current vcf files through 
vcf2abook (both from stdin or from explicit filename) and if works fine. 
However, any file created by abook2vcf will throw the error that I mentioned 
earlier, regardless of whether it is through stdin or if I create the file and 
explicitly name in as a first argument to vcf2abook. 

Thanks again for all your hard work.

**Comment by jspricke** [comment]
Can you send me your vcf file by email? Maybe you can build a minimal version with dummy values.

**Comment by coachshea** [comment]
I would be happy to do that, but as far as I can tell (I apologize if I'm 
missing something) your email isn't public. If you don't want to make it 
public, send me an email coachshea@fastmail.com and I'll reply with the 
attachments.

Thanks again for everything.
