### ISSUE TITLE
Quick start documentation

### ISSUE THREAD

**Issue by tjex** [jspricke/python-abook#5]
Really keen to try out the script and also contribute if needed / possible from my end (skill level wise). 

But I'm missing any and all information how to use the script. 
Setup and build have worked fine, but running the script just executes and does not return any information (and therefore hints regarding what flags etc I need to be giving it).

Would be great to have that in the readme!

**Comment by tjex** [comment]
never mind, I missed the detail that its a library, and not a stand alone script...

**Comment by jspricke** [comment]
Hi @tjex it actually installs two command line tools: abook2vcf and vcf2abook. Would you be interested to improve the readme? Would be great!

**Comment by tjex** [comment]
ah ok cool. Yup, I can pepper a bit more info in there after I have a dig around 👍

**Comment by tjex** [comment]
will reopen then, in case anyone else comes here with the same query.

**Comment by tjex** [comment]
@jspricke is it possible that I change the readme to markdown format?

Or is that too annoying on your end?

**Comment by jspricke** [comment]
I think it needs to be rest for new due to: https://github.com/jspricke/python-abook/blob/master/setup.py#L7
